### ISSUE TITLE
Keyboard Input Support?

### ISSUE THREAD

**Issue by Kungger-git** [angelofallars/top-calculator#1]
I'm wondering if this could also accept keyboard inputs, to make the calculator feel more interactive from the numpad. Love this, btw.

**Comment by angelofallars** [comment]
Gonna work on it!

**Comment by angelofallars** [comment]
@Kungger-git [Keyboard support has been implemented.](https://angelo.is-a.dev/top-calculator/)

## [Keybindings](https://github.com/angelofallars/top-calculator/)

- ( 0-9 ) - Numbers
- ( . ) - Degree symbol
- ( + / = ) - Addition
- ( - ) - Subtraction
- (x / \*) - Multiplication
- ( / ) - Division
- ( % ) - Modulo (Remainder)
- ( Enter ) - Calculate
- ( Backspace ) - Delete/Clear
